name: Stable Pinggy Windows RDP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable Remote Desktop & Disable NLA
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        Set-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name "MaxIdleTime" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password
      run: |
        $admin = [adsi]"WinNT://./runneradmin,user"
        $admin.SetPassword("MyPassword123#")

    - name: Start Pinggy RDP Tunnel
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -R 0:localhost:3389 a.pinggy.io
