name: Free Windows RDP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable Remote Desktop & Disable NLA
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password
      run: |
        $admin = [adsi]"WinNT://./runneradmin,user"
        $admin.SetPassword("MyPassword123#")

    - name: Start Tunnel Keepalive
      run: |
        Invoke-WebRequest https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-pc-windows-msvc.zip -OutFile bore.zip
        Expand-Archive bore.zip -DestinationPath .
        while ($true) {
            .\bore.exe local 3389 --to bore.pub
            Start-Sleep -Seconds 2
        }
