name: Free Windows RDP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Create User and Start RDP
      run: |
        net user runneradmin MyPassword123# /add || net user runneradmin MyPassword123#
        net localgroup administrators runneradmin /add || echo "Already admin"
        echo "Starting Tunnel..."
        ssh -p 443 -R 0:localhost:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 a.pinggy.io
